// batch_norm.v

// STREAM ORDER (must match conv2d_matmul output order):
//   Pixel 0 (Ch 0, 1, ... C_OUT-1) -> Pixel 1 (Ch 0, 1, ... C_OUT-1) -> ...
//   This is "Channel-Interleaved" or "Position-First" order.
//
// Example for Stage 1 (C_OUT=64, PIXELS_PER_CH=2048):
//   Cycle 0: Pixel 0, Ch 0  -> ch_idx=0
//   Cycle 1: Pixel 0, Ch 1  -> ch_idx=1
//   ...
//   Cycle 63: Pixel 0, Ch 63 -> ch_idx=63
//   Cycle 64: Pixel 1, Ch 0  -> ch_idx=0

// =============================================================================
//
// PURPOSE:
// Applies Batch Normalization to a stream of pixels coming from conv2d_matmul.
//
// HOW IT WORKS (the simple version):
// During training in Python, BatchNorm learns 4 values per channel:
//   gamma (γ), beta (β), mean (μ), variance (σ²)
//
// Before we load to FPGA, we "fold" these 4 values into just 2:
//   A = gamma / sqrt(variance + epsilon)      <- called SCALE
//   B = beta  - (A * mean)                    <- called BIAS
//
// Then on the FPGA, for every pixel x:
//   y = (A * x) + B
//
// That is it. One multiply and one add. No sqrt. No division.
//
// PIPELINE (2 stages, 2 cycle latency, 1 pixel per cycle throughput):
//
//   Cycle 1 (Stage 1): y_partial = in_data * scale_mem[ch_idx]   (Q16.16)
//   Cycle 2 (Stage 2): out_data  = (y_partial >> 8) + bias_mem[ch_idx]  (Q8.8)
//
// STREAM ORDER (must match conv2d_matmul output order):
//   Channel 0 all pixels → Channel 1 all pixels → ... → Channel C_OUT-1
//   Within each channel: row by row, column by column
//
// FIXED POINT FORMAT:
//   All data is Q8.8 signed:
//     - 1 sign bit
//     - 7 integer bits
//     - 8 fractional bits
//   Real value = register_value / 256
//
// PARAMETER FILES (generated by Python export script after training):
//   SCALE_FILE : C_OUT lines, each line is a 4-digit hex value for A
//   BIAS_FILE  : C_OUT lines, each line is a 4-digit hex value for B
// =============================================================================

module batch_norm #(

    // -------------------------------------------------------------------------
    // ARITHMETIC
    // -------------------------------------------------------------------------
    parameter DATA_W     = 16,          // bits per sample (signed Q8.8)
    parameter FRAC_W     = 8,           // number of fractional bits

    // -------------------------------------------------------------------------
    // TENSOR SHAPE
    // -------------------------------------------------------------------------
    parameter C_OUT      = 64,          // number of output channels
    parameter H_OUT      = 32,    
    parameter W_OUT      = 64,
    // -------------------------------------------------------------------------
    // PARAMETER FILES
    // -------------------------------------------------------------------------
    parameter SCALE_FILE = "G:/0. Sarah/0. Files_Sarah/4. GP Docs/singleline/bn_scale.hex",   // A = gamma / sqrt(var + eps)
    parameter BIAS_FILE  = "G:/0. Sarah/0. Files_Sarah/4. GP Docs/singleline/bn_bias.hex"     // B = beta  - A * mean

)(
    input  wire                  clk,
    input  wire                  rst_n,        // active-low synchronous reset

    // -------------------------------------------------------------------------
    // INPUT STREAM  (from conv2d_matmul)
    // -------------------------------------------------------------------------
    input  wire                  in_valid,     // upstream says (CNN): data is valid
    output wire                  in_ready,     // we say: ready to accept(BN)
    input  wire [DATA_W-1:0]     in_data,      // one pixel, Q8.8 signed
    
    // -------------------------------------------------------------------------
    // OUTPUT STREAM  (to silu)
    // -------------------------------------------------------------------------
    output wire                  out_valid,    // we say: output data is valid(BN)
    input  wire                  out_ready,    // downstream says: ready to accept(SILU OR FIFO)
    output wire [DATA_W-1:0]     out_data
);


    // =========================================================================
    // PARAMETER MEMORIES  (A and B, one value per channel)
    // =========================================================================
    // These are read-only after $readmemh loads them.
    // scale_mem[c] = A for channel c = gamma[c] / sqrt(var[c] + eps)
    // bias_mem[c]  = B for channel c = beta[c]  - A[c] * mean[c]

    reg [DATA_W-1:0] scale_mem [0:C_OUT-1];
    reg [DATA_W-1:0] bias_mem  [0:C_OUT-1];

    initial begin
        $readmemh(SCALE_FILE, scale_mem);
        $readmemh(BIAS_FILE,  bias_mem);
    end


    // =========================================================================
    // CHANNEL AND PIXEL COUNTERS
    // =========================================================================
    // ch_idx  : which channel is the current pixel from?  (0 to C_OUT-1)
    // pix_cnt : which pixel are we on inside this channel? (0 to PIXELS_PER_CH-1)
    //
    // Example for Stage 1 (C_OUT=64, PIXELS_PER_CH=2048):
    //
    //   pixel 0    → ch_idx=0,  pix_cnt=0
    //   pixel 1    → ch_idx=0,  pix_cnt=1
    //   ...
    //   pixel 2047 → ch_idx=0,  pix_cnt=2047  (last pixel of channel 0)
    //   pixel 2048 → ch_idx=1,  pix_cnt=0     (first pixel of channel 1)
    //   ...
    //   pixel 131071 → ch_idx=63, pix_cnt=2047 (last pixel of last channel)

    reg [$clog2(C_OUT)-1:0]         ch_idx;


    // =========================================================================
    // PIPELINE STAGE REGISTERS
    // =========================================================================

    // Stage 1: holds result of multiply
    // in_data * scale_mem[ch_idx] = Q8.8 * Q8.8 = Q16.16 (32 bits)
    reg                       s1_valid;      // stage 1 has valid data
    reg [DATA_W-1:0]          s1_bias;       // bias saved here for stage 2
                                             // (saved now because ch_idx will advance next cycle)
    reg signed [2*DATA_W-1:0] s1_product;    // 32-bit multiply result Q16.16

    // Stage 2: holds final result after truncation and bias add
    reg                       s2_valid;      // stage 2 has valid data
    reg [DATA_W-1:0]          s2_result;     // final output Q8.8


    // =========================================================================
    // HANDSHAKE ASSIGNMENTS
    // =========================================================================
    // This module is a pure pipeline with no internal FIFO.
    // It moves exactly when the downstream (silu) moves.
    //
    //   in_ready  = out_ready   means: "I can accept if you can consume"
    //   out_valid = s2_valid    means: "my output is valid when stage 2 has data"
    //   out_data  = s2_result   means: "my output is whatever stage 2 computed"

    assign in_ready = !s1_valid || out_ready;
    assign out_valid = s2_valid;
    assign out_data  = s2_result;


    // =========================================================================
    // PIPELINE LOGIC
    // =========================================================================

    always @(posedge clk or negedge rst_n) begin

        // ---------------------------------------------------------------------
        // RESET: clear everything
        // ---------------------------------------------------------------------
        if (!rst_n) begin
            ch_idx     <= 0;
           // pix_cnt    <= 0;
            s1_valid   <= 1'b0;
            s1_bias    <= {DATA_W{1'b0}};
            s1_product <= {(2*DATA_W){1'b0}};    
            s2_valid   <= 1'b0;
            s2_result  <= {DATA_W{1'b0}};

        // ---------------------------------------------------------------------
        // NORMAL OPERATION: pipeline advances only when out_ready is HIGH
        // Because in_ready = out_ready, upstream also advances at same time
        // ---------------------------------------------------------------------
        end else begin

            // Stage 2 advances only if downstream can accept (or stage2 empty)
            if (!s2_valid || out_ready) begin
                s2_valid <= s1_valid;
                if (s1_valid)
                    s2_result <= ($signed(s1_product) >>> FRAC_W) + $signed(s1_bias);
            end

            // Stage 1 advances only if stage2 has room
            if (!s1_valid || out_ready) begin
                s1_valid <= in_valid;
                if (in_valid) begin
                    s1_product <= $signed(in_data) * $signed(scale_mem[ch_idx]);
                    s1_bias    <= bias_mem[ch_idx];
                    if (ch_idx == C_OUT - 1)
                        ch_idx <= 0;
                    else
                        ch_idx <= ch_idx + 1;
                end
            end

    end
    end

endmodule